%YAML:1.0

#common parameters
imu_topic: "/IMU_data"
image_topic: "/camera/top"
output_path: "/output/tmp/result.txt"         # vins outputs will be wrttento vins_folder_path + output_path

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0.104783039500300
   k2: -0.332155109887520
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 6.095227362870955e+02
   fy: 6.093598028960326e+02
   cx: 3.206646275869129e+02
   cy: 2.488417000065093e+02


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
ex_calib_result_path: "/config/nao/ex_calib_result.yaml"  # If you choose 1 or 2, the extrinsic calibration result will be written vins_folder_path + ex_calib_result_path.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   # data: [0, 0, 1,
   #       -1, 0, 0,
   #        0,-1, 0]
   data: [ 1.4690628265503602e-02, 7.3421052858598512e-02,
       9.9719282710933066e-01, -9.9987377129502142e-01,
       -4.9576332591132477e-03, 1.5095143216912466e-02,
       6.0520176334634690e-03, -9.9728870988776519e-01,
       7.3338954266891854e-02 ]
   # data: [  -0.00424082,  0.05518754,  0.998467,
   #          -0.99700424, -0.07734695,  0.00004053,
   #          0.07723061, -0.99547566,  0.05535022]

#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [74.134e-03, 0, 256.233e-03]
   # data: [ 0.0306221, 0.00194611, 0.00235938 ]

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
# acc_n: 0.2          # accelerometer measurement noise standard deviation. #0.2
# gyr_n: 0.02         # gyroscope measurement noise standard deviation.     #0.05
# acc_w: 0.0002         # accelerometer bias random work noise standard deviation.  #0.02
# gyr_w: 2.0e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
# g_norm: 9.81007     # gravity magnitude
acc_n: 0.037019242958536196         # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.003435070053280316         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.0008323259020548661        # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.491879234946128e-05        # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 0   #if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
                     #also give the camera calibration file same as feature_tracker node
pattern_file: "/support_files/brief_pattern.yml"
voc_file: "/support_files/brief_k10L6.bin"
min_loop_num: 25


